version: '2'
services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile-webhook
    image: lhd-aurorabot:1.0
    container_name: lhd-aurorabot
    depends_on:
      - db
    volumes:
      - .:/opt
  db:
    image: postgres:latest
    ports:
      - "5432:5432"